# The conference service
conferenceServicePort = 8102
countryServiceUrl = "http://localhost:9000"
# countryServiceUrl = "http://country:9000"

# The database configs
[dbConfigs]
dbFilePath = "./db/h2"
user = "admin"
password = "admin"
