# Auto Generated Dockerfile
FROM ghcr.io/graalvm/native-image-community:17-ol8 as build

WORKDIR /app/build

COPY target/bin/conference_service_ballerina.jar .

RUN native-image -jar conference_service_ballerina.jar -H:Name=conference_service_ballerina --no-fallback -H:+StaticExecutableWithDynamicLibC

FROM gcr.io/distroless/base

WORKDIR /home/ballerina

COPY --from=build /app/build/conference_service_ballerina .

CMD ["./conference_service_ballerina"]
