### Request 1

GET http://localhost:8101/conferences

### Request 2

POST http://localhost:8101/conferences
Content-Type: application/json

{
    "id": "CONF-2019-001",
    "name": "WSO2Con"
}

### Request 3

GET http://localhost:8101/conferenceswithcountry
