[package]
org = "tharmigan"
name = "conference_service_ballerina"
version = "0.1.0"
distribution = "2201.9.0"

[[tool.persist]]
id = "generate-db-client"
targetModule = "conference_service_ballerina.db"
options.datastore = "mysql"
filePath = "persist/model.bal"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.3.0"

