# The conference service
conferenceServicePort = 8102
countryServiceUrl = "http://localhost:9000"

[conference_service_ballerina.db]
host = "localhost"
port = 3307
user = "dbuser"
password = "dbpwd123"
database = "conferencedb"

