name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ballerina-build:
    name: Ballerina Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ballerina
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.9.0
    
      - name: Build
        run: |
          bal build

      - name: Run Docker compose
        run: |
          docker-compose up -d
          sleep 120

      - name: Check Docker status
        run: docker ps

      - name: Run and Test
        run: bal run target/bin/conference_service_ballerina.jar  & sh .scripts/simple-test.sh

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
            java-version: '17'
            distribution: 'graalvm-community'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            set-java-home: 'false'

      - name: Build with GraalVM
        run: bal build --graalvm

      - name: Run and Test with GraalVM
        run: ./target/bin/conference_service_ballerina & sh .scripts/simple-test.sh

      - name: Stop Docker compose
        run: docker-compose down

  micronaut_build:
    name: Micronaut Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: micronaut
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
            java-version: '17'
            distribution: 'graalvm-community'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            set-java-home: 'true'

      - name: Build
        run: ./mvnw package

      - name: Run Docker compose
        run: |
          docker-compose up -d
          sleep 120

      - name: Check Docker status
        run: docker ps

      - name: Run and Test
        run: java  -jar target/conference_service_micronaut-1.0.jar & sh .scripts/simple-test.sh

      - name: Build with GraalVM
        run: ./mvnw package -Dpackaging=native-image

      - name: Run and Test with GraalVM
        run: target/conference_service_micronaut & sh .scripts/simple-test.sh

      - name: Stop Docker compose
        run: docker-compose down

  quarkus_build:
    name: Quarkus Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: quarkus
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
            java-version: '17'
            distribution: 'graalvm-community'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            set-java-home: 'true'

      - name: Build
        run: ./mvnw package -Dquarkus.package.type=uber-jar

      - name: Run Docker compose
        run: |
          docker-compose up -d
          sleep 120

      - name: Check Docker status
        run: docker ps

      - name: Run and Test
        run: java -jar target/conference_service_quarkus-1.0.0-runner.jar & sh .scripts/simple-test.sh

      - name: Build with GraalVM
        run: ./mvnw install -Dnative -Dquarkus.native.builder-image=graalvm

      - name: Run and Test with GraalVM
        run: target/conference_service_quarkus-1.0.0-runner & sh .scripts/simple-test.sh

      - name: Stop Docker compose
        run: docker-compose down

  springboot_build:
    name: Spring Boot Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring-boot
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
            java-version: '17'
            distribution: 'graalvm-community'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            set-java-home: 'true'

      - name: Build
        run: ./mvnw package

      - name: Run Docker compose
        run: |
          docker-compose up -d
          sleep 120

      - name: Check Docker status
        run: docker ps

      - name: Run and Test
        run: java -jar target/conference_service_springboot-1.0.0.jar & sh .scripts/simple-test.sh

      - name: Build with GraalVM
        run: ./mvnw -Pnative native:compile

      - name: Run and Test with GraalVM
        run: target/conference_service_springboot & sh .scripts/simple-test.sh

      - name: Stop Docker compose
        run: docker-compose down
  
