name: Performance Test

on: workflow_dispatch

jobs:
  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
            java-version: '17'
            distribution: 'graalvm-community'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            set-java-home: 'true'

      - name: Setup Python packages
        run: |
          pip3 install matplotlib
          pip3 install psrecord

      - name: Setup Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.9.0

      - name: Setup `wrk`
        run: |
          git clone https://github.com/wg/wrk.git wrk
          cd wrk
          make
          sudo cp wrk /usr/local/bin

      - name: Setup `wrk2`
        run: |
          git clone https://github.com/giltene/wrk2.git wrk2
          cd wrk2
          make
          mv wrk wrk2
          sudo cp wrk2 /usr/local/bin

      - name: Replace `gdate` usage with `date`
        run: |
          sed -i 's/gdate/date/g' run.sh
          sed -i 's/gdate/date/g' build.sh
        working-directory: ballerina/.scripts

      - name: Run Performance Test
        run: python3 performTest.py
        working-directory: .performance

      - name: Generate Report
        run: bal run
        working-directory: .report

      - name: Output Report
        run:
          cat ./report.md >> $GITHUB_STEP_SUMMARY
